[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI-Powered Storytelling: Techniques and Strategies for Innovative Narrative Creation with Artificial Intelligence"
